version: "3.5"

services:
  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/selenoid:ro
      - ./video:/opt/selenoid/video
    command:
      - "-limit"
      - "5"
      - "-conf"
      - "/etc/selenoid/browsers.json"
      - "-video-output-dir"
      - "/opt/selenoid/video"
    networks:
      - selenoid

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command:
      - "--selenoid-uri"
      - "http://selenoid:4444"
    networks:
      - selenoid

  selenoid-video:
    image: aerokube/video-recorder:latest-release
    container_name: selenoid-video
    volumes:
      - ./video:/opt/selenoid/video
    networks:
      - selenoid

networks:
  selenoid:
    driver: bridge
